### ISSUE TITLE
CSS sourcemap generation causing issue with JS sourcemap generation

### ISSUE THREAD

**Issue by kp-entrust** [Bluskript/vite-plugin-inline-css-modules#5]
**Description**
Vite currently supports CSS sourcemap only on dev, not on build. It also supports JS sourcemap on both environments. When this plugin is installed in a Vite codebase, the build process is unable generate the CSS sourcemap. This issue also causes the JS sourcemap from being generated fully.

**Error**
"Sourcemap is likely to be incorrect: a plugin (inline-css-modules) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help"

**Versions:**
vite 3.0.0
vite-plugin-inline-css-modules 0.0.6

**Steps to reproduce:**
1. Start with a fresh `vite create vite@latest app --template react-ts`
2. Make sure `build.sourcemap` is set to `true` in `vite.config.js`
3. `npm run build`
4. Notice the built files in `dist` has a working JS sourcemap
5. `npm i vite-plugin-inline-css-modules`
6.  `import { inlineCssModules } from `vite-plugin-inline-css-modules` and call it in the `plugins[]` in `vite.config.js`
7. `npm run build`
8. Notice the built files in `dist` has a broken JS sourcemap (with much lower file size compared to previous)

**Comment by bluskript** [comment]
hey @kp-entrust ! Can you try with `vite-plugin-inline-css-modules@0.0.7`? I disabled sourcemap generation and it seemed to get rid of the warnings and sourcemaps still seem to be working as expected.

**Comment by kp-entrust** [comment]
That seems to have worked. Thank you!
